export const shops = [
  {
    id: "",
    name: "Drug 24",
    url: "/shop/drug-24",
    products: [
      {
        id: "1",
        name: "Paracetamol",
        price: 21.95,
        image: "./images/products/paracetamol.webp",
        shop: "Drug 24",
      },
      {
        id: "2",
        name: "Ibuprofen",
        price: 15.2,
        image: "./images/products/ibuprofen.webp",
        shop: "Drug 24",
      },
      {
        id: "3",
        name: "Tylonel",
        price: 15.55,
        image: "./images/products/tylonel.webp",
        shop: "Drug 24",
      },
      {
        id: "4",
        name: "Diclofenac",
        price: 31.99,
        image: "./images/products/diclofenac.webp",
        shop: "Drug 24",
      },
    ],
  },
  {
    id: "",
    name: "Pharmacy",
    url: "/shop/pharmacy",
    products: [
      {
        id: "5",
        name: "Paracetamol",
        price: 22.99,
        image: "./images/products/paracetamol.webp",
        shop: "Pharmacy",
      },
      {
        id: "6",
        name: "Ibuprofen",
        price: 14.45,
        image: "./images/products/ibuprofen.webp",
        shop: "Pharmacy",
      },
      {
        id: "7",
        name: "Tylonel",
        price: 15.26,
        image: "./images/products/tylonel.webp",
        shop: "Pharmacy",
      },
      {
        id: "8",
        name: "Diclofenac",
        price: 33.45,
        image: "./images/products/diclofenac.webp",
        shop: "Pharmacy",
      },
    ],
  },
  {
    id: "",
    name: "Walgreens Company",
    url: "/shop/walgreens-company",
    products: [
      {
        id: "9",
        name: "Paracetamol",
        price: 25.16,
        image: "./images/products/paracetamol.webp",
        shop: "Walgreens Company",
      },
      {
        id: "10",
        name: "Ibuprofen",
        price: 13.99,
        image: "./images/products/ibuprofen.webp",
        shop: "Walgreens Company",
      },
      {
        id: "11",
        name: "Tylonel",
        price: 15.75,
        image: "./images/products/tylonel.webp",
        shop: "Walgreens Company",
      },
      {
        id: "12",
        name: "Diclofenac",
        price: 32.87,
        image: "./images/products/diclofenac.webp",
        shop: "Walgreens Company",
      },
    ],
  },
  {
    id: "",
    name: "CVS Health",
    url: "/shop/cvs-health",
    products: [
      {
        id: "13",
        name: "Paracetamol",
        price: 23.75,
        image: "./images/products/paracetamol.webp",
        shop: "CVS Health",
      },
      {
        id: "14",
        name: "Ibuprofen",
        price: 14.55,
        image: "./images/products/ibuprofen.webp",
        shop: "CVS Health",
      },
      {
        id: "15",
        name: "Tylonel",
        price: 15.99,
        image: "./images/products/tylonel.webp",
        shop: "CVS Health",
      },
      {
        id: "16",
        name: "Diclofenac",
        price: 32.25,
        image: "./images/products/diclofenac.webp",
        shop: "CVS Health",
      },
    ],
  },
  {
    id: "",
    name: "Walmart",
    url: "/shop/walmart",
    products: [
      {
        id: "17",
        name: "Paracetamol",
        price: 24.15,
        image: "./images/products/paracetamol.webp",
        shop: "Walmart",
      },
      {
        id: "18",
        name: "Ibuprofen",
        price: 16.35,
        image: "./images/products/ibuprofen.webp",
        shop: "Walmart",
      },
      {
        id: "19",
        name: "Tylonel",
        price: 14.55,
        image: "./images/products/tylonel.webp",
        shop: "Walmart",
      },
      {
        id: "20",
        name: "Diclofenac",
        price: 31.79,
        image: "./images/products/diclofenac.webp",
        shop: "Walmart",
      },
    ],
  },
];
